### ISSUE TITLE
Can't generate cpg_edges.csv case of ast.expressions.StringExpression cannot be cast to ast.functionDef.ParameterList

### ISSUE THREAD

**Issue by lujunsincerely** [malteskoruppa/phpjoern#2]
eric@eric:~/Documents/java-research/NAVEX/joern-dev$ ./phpast2cpg nodes.csv rels.csv 
Exception in thread "main" java.lang.ClassCastException: ast.expressions.StringExpression cannot be cast to ast.functionDef.ParameterList
        at tools.php.ast2cpg.PHPCSVEdgeInterpreter.handleFunction(PHPCSVEdgeInterpreter.java:528)
        at tools.php.ast2cpg.PHPCSVEdgeInterpreter.handle(PHPCSVEdgeInterpreter.java:159)
        at inputModules.csv.csv2ast.CSV2AST.createASTEdges(CSV2AST.java:95)
        at inputModules.csv.csv2ast.CSV2AST.convert(CSV2AST.java:52)
        at inputModules.csv.csvFuncExtractor.CSVFunctionExtractor.getNextFunction(CSVFunctionExtractor.java:72)
        at tools.php.ast2cpg.Main.main(Main.java:73)

**Comment by lujunsincerely** [comment]
Here is my php file for analysis by php-ast using php7.0,then pass the nodes,csv and rels.csv to joern-dev, but it's generate exception as up listed; however, when my php file without any function defined,it's work well.

<?php

function sayHello($name)
{
    echo $name."hello world!";
}
sayHello("Eric ");

**Comment by enferas** [comment]
Hello,

I am facing the same problem. Did you find a solution for it ?
The functions are not supported in phpjoern ?

**Comment by SheltonShi** [comment]
I am facing the same problem.（

**Comment by JulianGR** [comment]
I don't know if the author will accept my [PR](https://github.com/malteskoruppa/phpjoern/pull/5) because the repo is archived now, but you can see how I managed to fix in my [PR](https://github.com/malteskoruppa/phpjoern/pull/5)

**Comment by peng-hui** [comment]
**Solution**: For `php-ast`, please use `v0.1.2`. Also, keep the version in `src/Parser.php` as `30` no matter what applications you want to analyze.

**Comment by wangweijied** [comment]
I am facing the same problem.
